model_list:
  - model_name: "gemma3"
    litellm_params: 
      model: "ollama/gemma3:latest"
      api_base: "http://ollama:11434"
  - model_name: "llava"
    litellm_params: 
      model: "ollama/llava:7b"
      api_base: "http://ollama:11434" 