model_list:
  - model_name: flux-sdxl               # whatever name you want downstream
    litellm_params:
      model: huggingface/black-forest-labs/FLUX.1-dev
      api_key: os.environ/HF_TOKEN
  - model_name: "llava"
    litellm_params: 
      model: "ollama/llava:7b"
      api_base: "http://ollama:11434" 